openapi: 3.0.1
info:
  title: YETwitter.Posts.Web
  version: '1.0'
tags:
  - name: Posts API
    description: >
      Сервис редактирования постов и рейтинга постов пользователей
      
servers:
  - url: 'https://localhost/api'
    description: URL for testing

paths:
  /v1/post:
    put:
      tags:
        - post
      operationId: create
      summary: Создать запись
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostModel'
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePostResponseModel'
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

    delete:
      tags:
        - post
      operationId: delete
      summary: Удалить запись
      parameters:
        - name: postId
          in: path
          description: Идентификатор записи
          required: true
          schema:
            type: string
            maxLength: 36
      responses:
        '204':
          description: Успешная операция
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                
    get:
      tags:
        - post
      operationId: queryPosts
      summary: Искать записи
      parameters:
        - name: query
          in: path
          description: Поисковая строка
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/pageLimit"
        - $ref: "#/components/parameters/pageSkip"
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryPostResponseModel'
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                
  /v1/post/{userId}:
    get:
      tags:
        - post
      operationId: getPostsByUser
      summary: Получить записи пользователя
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/pageLimit"
        - $ref: "#/components/parameters/pageSkip"
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryPostResponseModel'
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /v1/post/{hashTag}:
    get:
      tags:
        - post
      operationId: getPostsByHashTag
      summary: Получить записи по тегу
      parameters:
        - name: hashTag
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/HashTag"
        - $ref: "#/components/parameters/pageLimit"
        - $ref: "#/components/parameters/pageSkip"
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryPostResponseModel'
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                
  /v1/raiting/like:
    put:
      tags:
        - raiting
      operationId: like
      summary: Нравится запись
      parameters:
        - name: postId
          in: path
          description: Идентификатор записи
          required: true
          schema:
            type: string
            maxLength: 36
      responses:
        '204':
          description: Успешная операция
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

    delete:
      tags:
        - raiting
      operationId: dislike
      summary: Не нравится запись
      parameters:
        - name: postId
          in: path
          description: Идентификатор записи
          required: true
          schema:
            type: string
            maxLength: 36
      responses:
        '204':
          description: Успешная операция
        '400':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorProblemDetails'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  parameters:
    pageSkip:
      name: pageSkip
      in: query
      description: Смещение числа записей
      schema: 
        type: integer
    pageLimit:
      name: pageLimit
      in: query
      description: Максимальное число записей в ответе
      schema: 
        type: integer

  schemas:
    QueryPostResponseModel:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Post'
      additionalProperties: false
    CreatePostModel:
      required:
        - rawtext
      type: object
      properties:
        rawtext:
          type: string
          minLength: 2
          maxLength: 140
      additionalProperties: false
    CreatePostResponseModel:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          maxLength: 36
      additionalProperties: false
    Post:
      required:
        - text
      type: object
      properties:
        text:
          type: string
          minLength: 2
          maxLength: 140
        hashtags:
          type: array
          items:
            $ref: '#/components/schemas/HashTag'
        appeals:
          type: array
          items:
            $ref: '#/components/schemas/Appeal'
      additionalProperties: false
    HashTag:
      type: string
      description: 'Хэштег'
      example: '#elonmusk'
    Appeal:
      type: string
      description: 'Ссылка на пользователя'
      example: '@elonmusk'
    PaginationResponse:
      type: object
      properties:
        totalPages:
          type: number
        currentPage:
          type: number
    ProblemDetails:
      required:
        - title
        - status
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        status:
          type: integer
        traceId:
          type: string
      additionalProperties: false
    ErrorProblemDetails:
      allOf:
        - $ref: '#/components/schemas/ProblemDetails'
        - type: object
          properties:
            errors:
              type: object
      additionalProperties: false
