openapi: 3.0.1
info:
  title: YETwitter.Identity.Web
  version: '1.0'
tags:
  - name: Identity API
    description: >
      Сервис авторизации и хранения информации пользователей
paths:
  /api/v1/auth/login:
    post:
      tags:
        - auth
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginModel'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/auth/register:
    post:
      tags:
        - auth
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterModel'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/v1/auth/change-password:
    post:
      tags:
        - auth
      operationId: changePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordModel'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '500':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    ChangePasswordModel:
      required:
        - newPassword
        - password
      type: object
      properties:
        password:
          type: string
          format: password
        newPassword:
          type: string
          format: password
      additionalProperties: false
    LoginModel:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        rememberMe:
          type: boolean
        returnUrl:
          type: string
          nullable: true
      additionalProperties: false
    RegisterModel:
      required:
        - email
        - password
        - username
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      additionalProperties: false
    ResponseModel:
      required:
        - status
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      additionalProperties: false
    ProblemDetails:
      required:
        - title
        - status
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        details:
          type: string
        status:
          type: integer
        traceId:
          type: string
      additionalProperties: false
