@startuml Login
title 
== Auth Login
end title
skinparam BoxPadding 20

actor cl as "Client"

box Browser
   participant front as "Front App"
   participant browserstorage as "<i>Local Storage" #LightGray
end box

box Backend   
    participant identity as "Identity Service"
    database db as "Identity DB"
end box


== Check Token ==
cl -> front: Request some page
front -> browserstorage: Get JWT token data
front <-- browserstorage

alt token not found or expired
    cl <-- front: Show login page
else token valid
    cl <-- front: Show requested page
end

== Login page ==   
cl -> front: Enter creds 
front -> identity: Send creds

alt creds validation failed
    front <- identity: failed result
    cl <- front: Show validation errors
else creds validation success
    identity -> db: Check user exist
    identity <-- db

    alt user exist and password correct
        front <- identity: JWT token data
        front -> browserstorage: Save JWT token data
        front <-- browserstorage
        cl <- front: Hide login page
    else user exist, password not correct
        front <- identity: 401
        cl <- front: Show error
    else user not exist
        front <- identity: 401
        cl <- front: Show error
    end
end